version: '3'
services:
  patello.se: 
    image: nginx:latest
    container_name: patello.se
    volumes:
      - ../content:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80